name: Deploy DEV
on:
  push:
    branches: [ dev ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: npm install
      - name: Build
        env:
          VITE_COGNITO_DOMAIN: https://users-dev.testigoelectoral.org
          VITE_COGNITO_CLIENT_ID: 7klnfm6laerioopp6hnnd74853
        run: |
          env|grep "^VITE_" > .env
          npm run build
      - name: Publish APP
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_DEV }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_DEV }}
          AWS_REGION: "us-west-1"
          BUCKET: "testigoelectoral-webapp-dev"
        run: |
          aws s3 sync --acl public-read build/ s3://${BUCKET}
      - name: Invalidate cache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_DEV }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_DEV }}
          AWS_REGION: "us-west-1"
          CLOUDFRONT_ID: "E2YU023QM2FW9X"
        run: |
          aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_ID} --path "/*"
          
          
