name: Deploy DEV

on: workflow_call

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: npm install
      - name: Build
        env:
          VITE_API_DOMAIN: https://api-dev.testigoelectoral.org
        run: |
          env|grep "^VITE_" > .env
          npm run build
      - name: Publish APP
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_DEV }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_DEV }}
          AWS_REGION: "us-west-1"
          BUCKET: "testigoelectoral-webapp-dev"
        run: |
          find build -type f -exec gzip -9 {} \; -exec mv {}.gz {} \;
          aws s3 sync --delete --acl public-read --content-encoding gzip build/ s3://${BUCKET}
      - name: Invalidate cache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_DEV }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_DEV }}
          AWS_REGION: "us-west-1"
          CLOUDFRONT_ID: "E2YU023QM2FW9X"
        run: |
          aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_ID} --path "/*"
